spring.application.name=delivery

spring.datasource.url=jdbc:postgresql://172.31.253.3:5432/food
spring.datasource.username=postgres
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# kafka
spring.kafka.bootstrap-servers=http://172.31.253.3:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.streams.application-id=delivery-streams-app
spring.kafka.streams.bootstrap-servers=172.31.253.3:9092
spring.kafka.streams.properties.spring.json.trusted.packages=*